services:
  - type: web
    name: server-boletin-kexford
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: node src/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: APP_BASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: API_KEY
        sync: false
      - key: API_EMAIL
        sync: false

  - type: cron
    name: worker-boletin-kexford
    runtime: node
    plan: starter
    buildCommand: npm install && npx prisma generate
    startCommand: node src/worker-cron.js
    schedule: "*/5 * * * *"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: APP_BASE_URL
        sync: false
      - key: MAX_ATTEMPTS
        value: "3"
      - key: BATCH_SIZE
        value: "10"
      - key: RECOVERY_LIMIT_PER_RUN
        value: "10"
